### ISSUE TITLE
Is there any plan to support printing line numbers?

### ISSUE THREAD

**Issue by hengyunabc** [leibnitz27/cfr#72] opened 2019-12-30 09:09 UTC
I found some information about the line number.

https://github.com/leibnitz27/cfr/search?q=line+number&unscoped_q=line+number

**Comment by leibnitz27** [comment] 2020-01-05 09:02
I'm going to close this as a dupe of #73 - I know it's earlier, but that one's got an interesting discussion going and I don't want to fork discussion ;)

**Closed by leibnitz27** 2020-01-05 09:02 UTC
