### ISSUE TITLE
Discarded (popped) expressions can cause "not a statement" if not consumed into ignored locals. 

### ISSUE THREAD

**Issue by lab313ru** [leibnitz27/cfr#10] opened 2019-06-20 13:11 UTC
FILE (no copyright materials): [o_test.zip](https://github.com/leibnitz27/cfr/files/3310529/o_test.zip)

CFR:
```
public static String fib(String a) {
    int n = a.length();
    int n2 = n - 1;
    char[] arrc = new char[n];
    int n3 = (3 ^ 5) << 4 ^ 1;
    (3 ^ 5) << 3 ^ (3 ^ 5);
    int n4 = n2;
    int n5 = (2 ^ 5) << 3 ^ 2;
    while (n4 >= 0) {
        int n6 = n2--;
        arrc[n6] = (char)(a.charAt(n6) ^ n5);
        if (n2 < 0) break;
        int n7 = n2--;
        arrc[n7] = (char)(a.charAt(n7) ^ n3);
        n4 = n2;
    }
    return new String(arrc);
}
```

Fernflower:
```
public static String fib(String a) {
    int var10000 = (2 ^ 5) << 3 ^ 2;
    int var10001 = (3 ^ 5) << 3 ^ 3 ^ 5;
    int var10002 = (3 ^ 5) << 4 ^ 1;
    int var10003 = a.length();
    char[] var10004 = new char[var10003];
    boolean var10006 = true;
    int var5 = var10003 - 1;
    var10003 = var10002;
    int var3;
    var10002 = var3 = var5;
    char[] var1 = var10004;
    int var4 = var10003;
    var10001 = var10000;
    var10000 = var10002;

    for(int var2 = var10001; var10000 >= 0; var10000 = var3) {
        var10001 = var3;
        char var6 = a.charAt(var3);
        --var3;
        var1[var10001] = (char)(var6 ^ var2);
        if (var3 < 0) {
            break;
        }

        var10002 = var3--;
        var1[var10002] = (char)(a.charAt(var10002) ^ var4);
    }

    return new String(var1);
}
```

Optimizations are ok, but that line with the mathematical operation looks weird.:)

**Comment by leibnitz27** [comment] 2019-06-20 13:28
Thanks for checking the copyright! ;)

I don't think this is a bug, or even bad behaviour - the issue is the explicit pops (well, pop2) in the byte code - compute an expression, and then discard it.   

It's very deliberately discarded, and assigning it to an intermediate value is a bit dishonest.

Also, though, throwing away the calculation would be dishonest too.  (very much so if it was side effecting, or could throw an exception, even so with the above because, well, it IS being calculated).

To be honest, I think assigning it to a local is bad - that's not what the JVM is doing, and if possible, a decompiler should be honest!

I guess it's possible to add  a comment /* discarded value */, but that sort of thing (ignoring return values) happens all the time.

**Comment by lab313ru** [comment] 2019-06-20 13:32
It would be great to comment it or even don't show any such info.
It doesn't give you any interesting info, but in case of trying to compile it will give you an error.

**Comment by leibnitz27** [comment] 2019-06-20 13:40
Oh, that's a really good point.  Whoops!  Guess I'll have to consume (or find a cleaner way of not-a-statement)ing them.

Thanks.

**Comment by lab313ru** [comment] 2019-06-20 14:08
As for example, Krakatau output:
```
public static String fib(String s) {
    int i = s.length();
    char[] a = new char[i];
    int i0 = i - 1;
    while(true) {
        if (i0 >= 0) {
            int i1 = s.charAt(i0);
            int i2 = i0 + -1;
            int i3 = (char)(i1 ^ 58);
            a[i0] = (char)i3;
            if (i2 >= 0) {
                i0 = i2 + -1;
                int i4 = s.charAt(i2);
                int i5 = (char)(i4 ^ 97);
                a[i2] = (char)i5;
                continue;
            }
        }
        return new String(a);
    }
}
```

Looks great.:) Could you make it the same?)

**Comment by leibnitz27** [comment] 2019-06-20 14:18
Eh.  Here, I'm much less convinced.  This hides the fact that the bytecode has some operations in it.   
I definitely don't think it's the job of the decompiler to do constant folding - if the compiler hasn't done it, I want to know that!

Consider the difference between

1 | 2 | 4 | 8 | x

and 

x | 8 | 4 | 2 | 1

http://www.benf.org/other/cfr/constant-folding.html

**Comment by lab313ru** [comment] 2019-06-20 14:20
Thanks:) Ok, you're right.

**Closed** 2019-06-21 05:58 UTC
